### ISSUE TITLE
Discuss Integration with the Canvas API

### ISSUE THREAD

**Issue by JeremyEastham** [johndpjr/AgTern#102]
Someone suggested integrating AgTern with Howdy at one point, but Howdy does not have a public API. **However,** I recently discovered that **Canvas** has a public API! Our users could login with Canvas (OAuth2) or connect their Canvas account, and we could access basically everything in their Canvas account.

At a minimum, this would allow us to see what courses they are currently taking. This may also allow us to see what courses they have taken in the past, including assignments and even grades.

**Documentation:** https://canvas.instructure.com/doc/api/index.html
**Complete Official Guide:** https://community.canvaslms.com/t5/Canvas-Developers-Group/Canvas-APIs-Getting-started-the-practical-ins-and-outs-gotchas/ba-p/263685

There is even a [Python package](https://github.com/ucfopen/canvasapi) written by the [University of Central Florida](https://github.com/ucfopen) that would allow us to easily interface with the API. [Canvas](https://github.com/instructure/canvas-lms) is also completely open source.

**canvasapi Package Documentation:** https://canvasapi.readthedocs.io/en/stable/
**Examples:** https://canvasapi.readthedocs.io/en/stable/examples.html

### Example:
```python
# To Generate an API Token for Testing:
# 1. Login to Canvas (https://canvas.tamu.edu)
# 2. Go to your Account Settings (sidebar -> account -> settings)
# 3. Scroll down to "Approved Integrations" and click the "+ New Access Token" button
# 4. Name it and click "Generate Token"
#
# This token gives you access to everything that you can see in the Canvas interface through the API
# For normal users, these tokens are generated automatically using an OAuth2 flow

from canvasapi import Canvas

BASE_URL     = "https://canvas.tamu.edu"
ACCESS_TOKEN = "ACCESS TOKEN GOES HERE"

canvas  = Canvas(BASE_URL, ACCESS_TOKEN)
courses = canvas.get_courses()
for course in courses:
    print(f"{course.course_code}\n{course.name}\n")
```
### Output:
```
CHEM 107 502: 
22 FALL CHEM 107 502: GEN CHEM FOR ENGINEERS

CHEM-117:534,536,538,540,542,544,546,548,550,552,554,556,558,560,562,564
22 FALL CHEM 117 534-564: GEN CHEM FOR ENGR TUESDAY EVEN LABS

ENGR-102:203,207,208,212,213,215,216,217,218,221,401,402,403,412,416,421,426,463,466,468,469,472,473,474,501,502,503,504,506,507,508,509,510,511,512,513,514,516,517,518,520,521,522,523,524,525,526,527,528,529,530,531,533,534,535,536,537,538,539,549,550...
22 FALL ENGR 102 Multisection

ENGR-102:212,213,217,525
22 FALL ENGR-102 Sections 212, 213, 217, 525: ENGR LAB I COMPUTATION

...
```

This integration could allow us to add more detail to an AgTern user's profile and give us more information to tailor our searches to each specific user. This data would not be displayed publicly since some of this information (grades, etc) is sensitive. We need to be clear about what data we are accessing, what we are using it for, and if we are storing that data.

**Comment by johndpjr** [comment]
Out-of-scope of the project for now, but will certainly consider it when we build profiles of students. However, I think the effort put into developing this solution just to view classes would be too much effort for the return it provides (a slightly better understanding of the student). We would also need to attach semantic meaning to each course and its relevance to subjects,
