### ISSUE TITLE
Research job boards

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#110]
### Context

Scaling our web-scraping tools might be difficult if we don't use job boards that do most of the hard work already. As discussed, this might have some advantages at the cost of disadvantages. Anyway, this task is just a preliminary research report on various functionality for the job boards.

### TODO

- [ ] Check out various job boards (e.g. [Indeed](https://www.indeed.com/), [Monster](https://www.monster.com/), and [LinkedIn Jobs](https://www.linkedin.com/jobs/)) and investigate their functionality. Try searching for internships and see what kind of data they give back, how good it is, and whether these services have a public API to access the data without scraping their site. Add this to the summary (detailed below)
- [ ] Reply to this ticket with a short summary of key similarities, differences, and challenges we might face by using job boards instead of scraping the company websites ourselves

### Notes

**Comment by johndpjr** [comment]
@ayoaina26 Just a friendly reminder to post some of your findings here as we discussed in the meeting and then we'll close this issue. Thanks!

**Comment by ayoaina26** [comment]
Got it!
https://www.jobspikr.com/blog/what-can-we-learn-from-linkedin-in-built-job-wrapping-process/
https://workello.com/is-linkedin-a-job-board/
https://customersuccess.linkedin.com/content/dam/customersuccess/integrationServices/Turn%20Your%20Job%20Listings%20into%20LinkedInJobs.pdf
https://maoviola.medium.com/a-complete-guide-to-web-scraping-linkedin-job-postings-ad290fcaa97f
https://booleanblackbelt.com/2009/04/is-linkedin-becoming-a-job-board/
