### ISSUE TITLE
Fix DigitalOcean instance

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#111]
### Context

Our [DigitalOcean instance](https://cloud.digitalocean.com/projects/9607c4b2-b333-4c5b-96c0-4f9f888f3975/resources?i=1070e8) has not been working due to cryptic error messages regarding memory usage. Let's get it back up and running!

### TODO

- [x] Access the [DigitalOcean instance](https://cloud.digitalocean.com/projects/9607c4b2-b333-4c5b-96c0-4f9f888f3975/resources?i=1070e8), get it to service requests, and have it run the code on the `dev` branch
- [x] Paste a link to the website in the Discord channel once it is working 

### Notes

Once complete with this, start #99 and make some scripts that can help automate our processes (research [CI/CD](https://en.wikipedia.org/wiki/CI/CD) and get inspired!).

**Comment by brendanehrman1** [comment]
Now accessible at [tx.ag/tern]().

**Comment by JeremyEastham** [comment]
I've also updated the original link (tx.ag/agtern) to point to the new address.

**Comment by brendanehrman1** [comment]
Thank you!
