### ISSUE TITLE
Setup OAuth login infrastructure

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#121]
### Context

Now that we want to track jobs, we need to have some kind of authentication lest bad actors access sensitive user data. Since CAS didn't seem to be an effective solution (#112), we should use OAuth instead. [OAuth](https://en.wikipedia.org/wiki/OAuth) is just an authentication protocol that is highly secure and allows us to authenticate and access user data without having their passwords. This is done via implicit login flows (think of when you login via Google on 3rd-party websites; we are doing essentially the same thing).

### TODO

- [ ] Set up the necessary functionality to use OAuth in our application (see the Notes for FastAPI OAuth docs)
- [ ] Authenticate the user using their `username` and `password` (no need for Google login, etc.)

### Notes

_You won't need to touch the frontend here. Use the [FastAPI OAuth docs](https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/) to get started with this. It will give you a good starting point. Remember to add any additional dependencies to the_ `requirements.txt` _file. Please let me know if you have any roadblocks- I've done a bit of this so far._

**Comment by JeremyEastham** [comment]
I created a basic (non-OAuth) username and password authentication API during TAMUhack. It's not connected to a database, but it might be useful to use as a reference or a starting point:
https://github.com/kalratanav/tamuhack_project/blob/main/backend/api/api.py
