### ISSUE TITLE
Expand LabelFrame and Text widgets as window is resized

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#15]
When the window is resized, the LabelFrame (`_lblfrm_internship_details`) and the Text (`_txtbox_internship_description`) widgets do not resize horizontally as seen in the image below.

### TODO

- [ ] As the window is resized, have the LabelFrame and the Text widgets resize dynamically to fill their parent frame, `InternshipDetailFrame`

![unused-space-agtern](https://user-images.githubusercontent.com/78290887/192146715-98219cbe-8ad5-40da-8b71-b25a2477e70d.png)

**Comment by brendanehrman1** [comment]
This may also be happening for the widgets in ProfileFrame. Please look into it!
