### ISSUE TITLE
Modularize Angular components

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#152]
## Context

Our Angular application is using Components everywhere - this is good and bad. Using Components without [Modules](https://angular.io/guide/architecture-modules) causes the Angular application to _load all Components at once_- which is incredibly inefficient and slow. If we moved everything into Modules, we could load them lazily (i.e. load them when needed). For example, if we open the Jobs page (and all the jobs components were in the Job module), then all the corresponding components _for the Job module_ are loaded _on request_. Right now when we go to the home page, it loads the toolbar, jobs page, login page, sign up page, etc.

## TODO

- [ ] Reorganize and refactor the Angular components into [Modules](https://angular.io/guide/architecture-modules) and [lazily load](https://angular.io/guide/lazy-loading-ngmodules) them in the routes

## Notes

**Comment by JeremyEastham** [comment]
Another way to achieve this is by using Angular's new [Standalone Components](https://angular.io/guide/standalone-components). If done in this way, each component would become its own mini-module with its own dependencies that can be lazily loaded independently.
