### ISSUE TITLE
Add sign-in and up with Google buttons

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#167]
## Context

In order to continue with OAuth, we need frontend functionality to allow any user to sign up with Google and sign in with Google.

## TODO

- [ ] Add "Sign in with Google" and "Sign up with Google" to the login and sign up pages, respectively. Make it look presentable! See both figures below for some initial ideas.

## Notes

_This ticket does not implement OAuth, it just provides simple buttons (that do nothing)._

![image](https://github.com/johndpjr/AgTern/assets/78290887/2694d6e4-7a63-4e8d-9475-c4d7f86334dd)
**Figure 1. An example of what a sign-in button might look like.**

![image](https://github.com/johndpjr/AgTern/assets/78290887/69d6b949-9d3d-429e-88f9-cc7b63550f48)
**Figure 2. An example of the sign-up with Google in the sign up context.**

**Comment by sidd3103** [comment]
Hi. Can I work on this?
