### ISSUE TITLE
Add Google Sign-Up button

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#206]
## Context

Right now, we just have a "Sign in with Google" button on the login page, but we don't have one on the sign-up page. @johndpjr has tried putting the button on the sign-up page, but with no success. For some reason, you cannot initialize two instances of this button so that they can appear on both login and sign-up components.

## TODO

- [ ] Add a sign-up with Google button (same as the login with Google button) to the sign-up page (it should have the functionality of signing up with Google as well)

## Notes

**Comment by Jwdegames** [comment]
Note: I got it to mostly work, but there is a bug where if you go directly from the login page to signup or vice versa, then the google sign up button disappears. Perhaps it's not clearing the component before loading the other one and that's causing the issue?

**Comment by Jwdegames** [comment]
I fixed the issue by adding a 100 ms delay for the sign in button
