### ISSUE TITLE
Add MacOS scroll functionality

### ISSUE THREAD

**Issue by brendanehrman1** [johndpjr/AgTern#25]
### TODO
- [ ]  Find a way to determine the OS of the system that the application is being run on (maybe `import platform`?)
- [ ] Edit `_on_mousewheel` in `vertical_scrolled_frame` to correctly calculate value to scroll for all OS systems

### Notes
MacOS `event.delta` is a multiple of 1, whereas Windows `event.delta` is a multiple of 120
Don't worry about editing Linux handling (unless you find that `Button-4` and `Button-5` are used elsewhere in Windows/MacOS)

**Comment by johndpjr** [comment]
Closing this as nothing has happened in a month and it seems like this could be brought up later if the need is there
