### ISSUE TITLE
Create AgTern Wiki

### ISSUE THREAD

**Issue by JeremyEastham** [johndpjr/AgTern#30]
Many open source repositories use GitHub Wikis to provide documentation about their project. I suggest that we create Wiki pages that summarize information that we discuss at meetings to reference when we are working on the project. This would be especially beneficial for project members that miss a meeting or members that are new to the libraries that we are using.

### Suggested Pages:
- General
  + Current Goals
  + Meeting Summaries
  + Imports
- Configuration & Data
  + scraping_config.json
  + db.json
  + config.ini
- Frontend
  + TKinter
    + Frames and Widgets
    + Layout (Grid, Sticky, Pack)
    + Vars (IntVar, StringVar, BooleanVar)
- Backend
  + Selenium
    + WebDriver Installation
  + XPaths
  + Regular Expressions

More information: https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis
Example of a large Wiki (SymPy): https://github.com/sympy/sympy/wiki

**Comment by johndpjr** [comment]
Created Wiki - will add more tickets for more specific documentation later
