### ISSUE TITLE
Style and formatting guidelines

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#31]
Since our project is becoming larger and more developed, we should enforce a certain formatting and style. There are many tools out there that do this, but [autopep8](https://pypi.org/project/autopep8/) formats code automatically according to [PEP8](https://peps.python.org/pep-0008/) style guidelines. Also, additional tools like [Flake8](https://flake8.pycqa.org/en/latest/#) can do linting. Any thoughts?

**Comment by brendanehrman1** [comment]
I'm thinking of adding some pre-commit hooks to validate changes and format according to autopep8. Should make it so that as long as pre-commit is installed, all commit changes will be automatically checked and formatted.
