### ISSUE TITLE
Make CSV of company names and links

### ISSUE THREAD

**Issue by johndpjr** [johndpjr/AgTern#4]
### TODO
- [ ] Take a look at this [site](https://www.computersciencedegreehub.com/internships-fortune-500-companies/) that contains Fortune 500 companies offering CS internships. This is a good starting point for our MVP.
- [ ] Create a CSV file called `companies.csv` in the `agtern` directory that contains a row for each company containing the following information: company_name,"job_portal_url"

### Notes
**Notice that company_name is separated from job_portal_url by the comma character (,). Also notice that job_portal_url is wrapped in double quotes (").** Since URLs can contain commas, we don't want the CSV parser to detect things as separate values, so wrap job_portal_url in double quotes like above.

For example, the first company is Walmart. Follow that link to get to their [student programs](https://careers.walmart.com/undergraduate-internships), then click on ["See all opportunities"](https://careers.walmart.com/results?q=2022&page=1&sort=rank&expand=department,brand,type,rate&jobCareerArea=all). This is the link that we want. _Try to find similar "job board" type portals for each company that contains **actual jobs**._

So, the beginning of the file `companies.csv` should look like this:
```
Walmart,"https://careers.walmart.com/results?q=2022&page=1&sort=rank&expand=department,brand,type,rate&jobCareerArea=all"
```

_Again, notice the comma after Walmart and the URL wrapped in double quotes._

### Challenge
For practice, use Selenium to scrape all of this and create a CSV automatically! Automate this! I believe in you Steven!
_Afterward, make sure that the links point to the job portals as expected._

**Comment by ZeroMeOut** [comment]
Hello, can I also try doing this challenge? I'm trying to improve my python skills.

**Comment by johndpjr** [comment]
Yeah anyone can do it!
