### ISSUE TITLE
Create config.ini with default values if it does not exist

### ISSUE THREAD

**Issue by JeremyEastham** [johndpjr/AgTern#53]
Multiple people have accidentally committed their config files. One way to solve this problem is to add `config.ini` to `.gitignore`, but that means that `config.ini` will not exist when the program is run for the first time. If you delete `config.ini`, the program currently fails with an error. The file is automatically created, but it is blank. The first time that a value is read, it raises a `KeyError`.

If `config.ini` does not exist, the file should be created with default values so the program can continue without errors.

**Comment by johndpjr** [comment]
Migrating to Angular; ending tkinter development. This configuration information will be stored on Student accounts in the server
