### ISSUE TITLE
Fix web scraper memory leak

### ISSUE THREAD

**Issue by JeremyEastham** [johndpjr/AgTern#68]
![oh_no.png](https://user-images.githubusercontent.com/34139712/200143835-1783148e-4771-4ff5-9a09-f53540543be2.png)

I thought that the Chrome instances were correctly being destroyed when the web scraper exits or crashes. Apparently, (at least sometimes) they are not!

This could be a huge issue on the server once we start running these jobs unattended.

**Comment by johndpjr** [comment]
Will look into this more, especially if Droplet starts breaking.

**Comment by JeremyEastham** [comment]
This issue has come back on the [backend/159/overhaul-scraping-backend](https://github.com/johndpjr/AgTern/tree/backend/159/overhaul-scraping-backend) branch due to #159.

**Comment by JeremyEastham** [comment]
The recurrence of this issue needs to be verified. Apparently, recent versions of Chrome continue to run even when closed. It is difficult to determine whether the source of the extra Chrome processes in Task Manager are supposed to be running or not. I'm closing this issue for now. We can reopen this if it becomes a problem down the line.

![image](https://github.com/johndpjr/AgTern/assets/34139712/0afa2b7d-b7dc-4a90-a3d1-0839b8392e19)
