### ISSUE TITLE
Migrate to Angular

### ISSUE THREAD

**Issue by JeremyEastham** [johndpjr/AgTern#77]
### We're all tired of Tkinter
Tkinter is adding unnecessary complexity and bugs to our project. Tkinter was simply not designed for a project of this scale.

We've given it a good chance, but it's time to move on.

With Angular, we can deploy to the web and utilize HTML, SCSS, and TypeScript to create a more user-friendly and bug-free experience. It should also massively improve our development pipeline, since there are very good, well supported libraries that we can use for things like GUI and API requests.

Let's create something we can be proud of!

**Comment by johndpjr** [comment]
With `dev` having been merged into `main`, I think we can safely say that `tkinter` is behind us- for good!
